# Generated by Django 5.2.8 on 2025-11-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
